### PR TITLE
Improve and fix caching of text surfaces

### PR DESCRIPTION
**Pull request by glebm**
1. Fixes text caching for links.
2. Implements text caching for section titles.
3. Cleanups to make this easier.

### CODE REVIEW

**Comment by pcercuei** [comment]
The changes look OK, but you cram several unrelated things inside one big commit without a description. This does not only "invalidate text surfaces on font change". Please try to separate the various atomic improvements into their own commits, it will be much easier for us to review the PR. Thanks!

**Comment by glebm** [comment]
@pcercuei This PR is only 130 lines, it shouldn't be difficult to review at all. I'd rather spend my time on something more impactful.

Explanation of related changes:

1. `initFont` and `Font` changed so that we may know when the font has actually changed (this way we don't renderer if a skin changed but the font didn't).

2. `Link` constructor had undefined behaviour (not initializing `rect.x` and `rect.y`), redundantly created surfaces. Cleaned it up while I was at it.

**Comment by pcercuei** [comment]
If you do several changes then just have several commits. Don't put everything into a big one.

And put the explanation in the commit messages.

**Comment by glebm** [comment]
Done

**Comment by pcercuei** [comment]
Looks much better, thanks.

Please sign all the commits so that I can merge them.

**Comment by glebm** [comment]
Done

**Pull request merged**
