### PR TITLE
Fix hardcoded values in selector menu.

### PR DESCRIPTION
**Pull request by uncletrunks**
Haven't tested, but this _should_ fix the lines cutting off at half resolution 620x480 devices.

### CODE REVIEW

**Comment by uncletrunks** [comment]
Tested and working.
image0

**Comment by pcercuei** [comment]
Please sign-off your commit (`git commit --amend -s`) then force-push your branch.

**Comment by uncletrunks** [comment]
Done, hopefully correctly.

**Comment by pcercuei** [comment]
@uncletrunks Do you have a real email address? I doubt t450s.localdomain is a real email host :)

**Comment by uncletrunks** [comment]
Alright, there we go.

**Comment by pcercuei** [comment]
Merged, thanks!

**Pull request merged**
