### PR TITLE
Fix memory leaks in SurfaceCollections

### PR DESCRIPTION
**Pull request by glebm**
Fixes leaks reported by ASAN by ensuring that the surfaces are cleaned up correctly.

### CODE REVIEW

**Comment by pcercuei** [comment]
I understand the need to fix memory leaks, but this looks strange to me - using smart pointers internally, then using `.get()` everywhere to get raw pointers. That's an accident waiting to happen.

Maybe having SurfaceCollection return shared pointers would make more sense? Would that be difficult to put in place?

**Comment by glebm** [comment]
From what I understand, these `Surface`s have a clear owner, the `SurfaceCollection`, so `shared_ptr` doesn't really make sense here.

**Comment by mthuurne** [comment]
If they have a clear owner, the best way to share them is to return a reference instead of a pointer. To deal with images that fail to load, you probably need something like a `DummySurface` which implements the same interface but doesn't actually do any work when called.

**Comment by glebm** [comment]
Sure it is. However, refactoring the interface is a separate issue.

**Comment by pcercuei** [comment]
I guess it's still an improvement over the status-quo, so I can merge. GMenu2X's code is so painful to read that any improvement is welcome.

**Pull request merged**
